services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      
    ports:
      - 5432:5432
    networks:
      - database
networks:
  database:
    driver: bridge
    name: database
