apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: todo-app
spec:
  selector:
    matchLabels:
      app: app-deployment
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
      - name: app-deployment
        image: olymahmudmugdho/todo-app-spring-react
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: configs
              key: DATABASE_URL
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: password
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
