apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: todo-app
  labels:
    app: local
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data
