services:
  backend:
    image: olymahmudmugdho/todo-app-backend
    container_name: backend-service 
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/todo_app
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=mysecretpassword
    networks:
      - database
networks:
  database:
    driver: bridge
    name: database
